name: r-main-wasm-host
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  - pcre2
  - zlib
  - xz
  - bzip2
  - libiconv
  - libflang
  - r-base
  - zstd
  - libarchive
  # For the r-py output: libpython statically linked into RPY executable.
  - python ==3.13.*
  - libpython ==3.13.*
  - libffi
  - sqlite
  - openssl