name: Build and Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Github-page

    steps:
      - uses: actions/checkout@v6

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment-wasm-build.yaml
          init-shell: bash
          environment-name: r-main-wasm-build

      - name: Set ncpus
        run: echo "ncpus=$(nproc --all)" >> $GITHUB_ENV

      - name: Build r-main
        shell: bash -l {0}
        run: |
          micromamba create -f environment-wasm-host.yaml --platform=emscripten-wasm32

          set -eux

          # to avoid errors like:
          #   clang++: error: unsupported option '-march=' for target 'wasm32-unknown-emscripten'
          # we just clear the flags here
          export CFLAGS=""
          export CXXFLAGS=""
          export LDFLAGS=""

          ./build.sh
       

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./glue

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5